cap-js/telemetry

lib/tracing/trace.js

@schiwekM could you please comment on the idea behind `_getDBTarget()`? why not simply use `req.target.name`? thanks

fix: get target for db span

---

lib/tracing/cds.js
lib/tracing/index.js
lib/tracing/okra.js
lib/tracing/trace.js
lib/utils.js

Without this change any handlers returning promises that reject where not being returned and therefor where being thrown onto the root of the application crashing the application.

fix: promise rejections crashing the app

---

lib/exporter/ConsoleSpanExporter.js
lib/tracing/trace.js

closes https://github.com/cap-js/telemetry/issues/70

feat: span hierarchy

---

README.md

re https://github.com/cap-js/telemetry/issues/93

clarify HOST_METRICS_LOG_SYSTEM

---

CHANGELOG.md
lib/tracing/index.js

feat: add support for double export

---

CHANGELOG.md
README.md
lib/exporter/ConsoleSpanExporter.js
lib/tracing/index.js
lib/tracing/trace.js
lib/utils.js
package.json
test/bookshop/package.json

feat: support for own, high resolution timestamps

---

.github/workflows/label-issues.yml

... as prerequisite to auto-detect new issues.

chore: Add workflow to label new issues

---

README.md

closes https://github.com/cap-js/telemetry/issues/142

@dynatrace/oneagent-sdk is not required

---

.github/dependabot.yml

re https://github.com/cap-js/telemetry/issues/161

chore: dependabot, plz update prod deps

---

lib/exporter/ConsoleSpanExporter.js
lib/tracing/cds.js
lib/tracing/trace.js
package.json
test/bookshop/package.json
test/bookshop/srv/admin-service.cds
test/bookshop/srv/admin-service.js
test/bookshop/test.http
test/tracing.test.js

closes https://github.com/cap-js/telemetry/issues/43

chore: cleanup attributes, improve cds.spawn handling, improve built-in ConsoleSpanExporter

---

CHANGELOG.md
lib/exporter/ConsoleSpanExporter.js
lib/index.js
lib/tracing/index.js
lib/tracing/trace.js
package.json
test/bookshop/package.json

closes https://github.com/cap-js/telemetry/issues/166

feat: Support for adding `@opentelemetry/instrumentation-runtime-node`

---

lib/metrics/db-pool.js

re https://github.com/cap-js/telemetry/issues/68

chore: cleanup meter name comments

---

lib/tracing/trace.js

closes https://github.com/cap-js/telemetry/issues/72

chore: add new versions of deprecated attributes

---

CHANGELOG.md
README.md
lib/tracing/index.js

feat(to-dynatrace)!: @opentelemetry/exporter-trace-otlp-proto -> export via otel

---

CHANGELOG.md
lib/index.js
lib/metrics/index.js
lib/tracing/index.js
package.json

fix: provide tracerProvider and meterProvider explicitly 

---

CHANGELOG.md
lib/tracing/index.js
lib/tracing/trace.js
package.json

closes https://github.com/cap-js/telemetry/issues/255

fix: use url.path || http.target for sampling decision

---

CHANGELOG.md
lib/tracing/index.js

closes https://github.com/cap-js/telemetry/issues/281

feat: pass custom config to span processor

---

CHANGELOG.md
README.md
jest.config.js
lib/index.js
lib/tracing/index.js
lib/tracing/trace.js
package.json
test/bookshop/lib/MyIgnoreIncomingRequestHook.js
test/bookshop/package.json
test/bookshop/test.http
test/logging.test.js
test/tracing.test.js

closes https://github.com/cap-js/telemetry/issues/268

feat: support for loading instrumentation hooks

---

lib/utils.js

support of the cloud-logging tag as in cap, see: https://github.com/cap-js/docs/pull/1441/files

fix: support cloud-logging tag on ups

---

CHANGELOG.md
lib/tracing/trace.js

closes https://github.com/cap-js/telemetry/issues/302

fix: database span attributes

---

CHANGELOG.md
cds-plugin.js
package.json

fixes https://github.com/cap-js/telemetry/issues/331

fix: resilient version lookup

---

.github/workflows/hana.yml
CHANGELOG.md
jest.config.js
lib/tracing/cds.js
lib/tracing/trace.js
package.json
test/_db_spans.js
test/tracing-attributes.test.js

closes https://github.com/cap-js/telemetry/issues/351

fix: missing SQL-related attributes

---

CHANGELOG.md
lib/exporter/ConsoleSpanExporter.js
lib/tracing/trace.js
package.json
test/_db_spans.js

Resolves https://github.com/cap-js/telemetry/issues/337

feat: adopt stable attributes

---

CHANGELOG.md
lib/metrics/db-pool.js
lib/metrics/queue.js
lib/tracing/trace.js
package.json
test/metrics-outbox-multitenant.test.js

closes https://github.com/cap-js/telemetry/issues/362

fix: ensure initialization of persistent queue statistics
