lib/tracing/index.js
lib/tracing/trace.js
package.json
test/bookshop/package.json
test/bookshop/test.http

closes https://github.com/cap-js/telemetry/issues/47

fix: [seconds, nanoseconds] since unix epoch

---

CHANGELOG.md
README.md
lib/metrics/index.js
lib/tracing/index.js
lib/utils.js
package.json
test/bookshop/package.json

closes https://github.com/cap-js/telemetry/issues/52
closes https://github.com/cap-js/telemetry/issues/58

feat: preset for SAP Cloud Logging

---

CHANGELOG.md
lib/exporter/ConsoleMetricExporter.js

example custom metric request counter:
```js
const cds = require('@sap/cds')
const { metrics } = require('@opentelemetry/api')
let counter
cds.middlewares.add((req, _, next) => {
counter.add(1, { 'sap.tenancy.tenant_id': req.tenant })
next()
})
cds.on('listening', () => {
/*
* UNOFFICIAL cds._telemetry.name is the SemanticResourceAttributes.SERVICE_NAME,
* which CURRENTLY is process.env.OTEL_SERVICE_NAME || PKG?.name || VCAP_APPLICATION?.name || 'CAP Application'
*/
const meter = metrics.getMeter(`${cds._telemetry.name}-meter`)
counter = meter.createCounter('req.counter')
})
module.exports = cds.server
```
outputs:
```txt
[telemetry] - req.counter of tenant "t1": {
attributes: { 'sap.tenancy.tenant_id': 't1' },
startTime: [ 1705354230, 96000000 ],
endTime: [ 1705354446, 736000000 ], …
```

feat: enable custom metrics

---

CHANGELOG.md
lib/metrics/index.js
lib/utils.js

According to APM docu for Dynatrace if a Dynatrace service instance cannot be used, a user provided service instance with the name containing "dynatrace" shall be used.
PR adds this support because also we need it in our app :)
BR,
Marten

feat: support for Dynatrace credentials via user-provided service

---

lib/tracing/index.js

ignoreIncomingPath was not working because we were trying to check cds.env.requires.telemetry.instrumentations.http however in our package.json configuration it is : "cds": {
"telemetry":{
"instrumentations": {
"http": {
"module": "@opentelemetry/instrumentation-http",
"class": "HttpInstrumentation",
"config":{
"ignoreIncomingPaths": [
"/dbHealth/*",
"/metrics"
]
}
}
}}}
So config field is missing .

fix: ignoreIncomingPaths -> config.ignoreIncomingPaths

---

CHANGELOG.md
README.md
lib/metrics/index.js
test/metrics.test.js
test/tracing.test.js

supersedes https://github.com/cap-js/telemetry/pull/100
thanks @marcsst!

feat!: ignore all `system.*` metrics by default

---

CHANGELOG.md
lib/metrics/index.js

after consultation with the experts, DELTA is a good default in general

feat(metrics): temporalityPreference ??= DELTA

---

CHANGELOG.md
lib/exporter/ConsoleSpanExporter.js
lib/metrics/db-pool.js

closes https://github.com/cap-js/telemetry/issues/109

fix(ConsoleSpanExporter): identify first-level spans

---

CHANGELOG.md
lib/metrics/index.js
lib/tracing/index.js
lib/utils.js
package.json
test/bookshop/_default-env.json

closes https://github.com/cap-js/telemetry/issues/131

fix: only throw in case of missing creds if respective kind is configured

---

CHANGELOG.md
lib/index.js
package.json

closes https://github.com/cap-js/telemetry/issues/177

fix: detect build job started via `@sap/cds-dk/bin/cds.js`

---

CHANGELOG.md
lib/metrics/index.js
lib/tracing/index.js
lib/utils.js

The plugin currently does not support UPS for Cloud Logging. This is described in the documentation:
https://help.sap.com/docs/cloud-logging/cloud-logging/ingest-via-cloud-foundry-runtime?locale=en-US&version=Cloud#procedures
UPS for Cloud Logging is enabled with this extension.

feat: SAP Cloud Logging as user provided service

---

CHANGELOG.md
lib/exporter/ConsoleMetricExporter.js

closes https://github.com/cap-js/telemetry/issues/222

fix: adjust attribute name to process.cpu.state

---

CHANGELOG.md
lib/tracing/trace.js
package.json
test/tracing-attributes.test.js

non-fork version of https://github.com/cap-js/telemetry/pull/271

feat: db.client.response.returned_rows

---

CHANGELOG.md
lib/index.js
lib/tracing/cds.js
lib/tracing/okra.js
lib/tracing/trace.js
lib/utils.js

Currently `SAP Passport` is only updated when `prepare` and `exec` are called, but it is required to update every time the database is called. Therefor this PR shifts the `SAP Passport` criteria to using `prom`. Which is the re use function `@cap-js/hana` uses inside its generic driver wrappers to promisify the native driver functions. Therefor by tracing the `prom` function it traces _all_* driver calls and ensures that the `SAP Passport` contains an unique trace ID which open telemetry can anchor itself onto. As without the round trip specific parent trace ID the open telemetry service provider will see the child trace timestamps outside of the parent trace window and try to adjust the timestamp into the parent trace time frame. Which gets especially confusing when the parent time frame …

fix: Keep SAP Passport up-to-date

---

lib/tracing/trace.js

Add check on possible undefined / null value in order to prevent crash. 
Fixing crash:
`TypeError: Cannot read properties of undefined (reading 'split') at _getRequestAttributes (/home/vcap/deps/0/node_modules/.pnpm/@cap-js+telemetry@1.0.1_@sap+cds@7.9.3_express@4.21.2_/node_modules/@cap-js/telemetry/lib/tracing/trace.js:152:63) at _getParentSpan (/home/vcap/deps/0/node_modules/.pnpm/@cap-js+telemetry@1.0.1_@sap+cds@7.9.3_express@4.21.2_/node_modules/@cap-js/telemetry/lib/tracing/trace.js:57:30) at trace (/home/vcap/deps/0/node_modules/.pnpm/@cap-js+telemetry@1.0.1_@sap+cds@7.9.3_express@4.21.2_/node_modules/@cap-js/telemetry/lib/tracing/trace.js:203:22) at wrapper (/home/vcap/deps/0/node_modules/.pnpm/@cap-js+telemetry@1.0.1_@sap+cds@7.9.3_express@4.21.2_/node_modules/@cap-js/telemetry/li …

Prevent undefined/null value

---

CHANGELOG.md
lib/tracing/trace.js
package.json
test/bookshop/server.js
test/bookshop/test.http
test/tracing.test.js

a stakeholder is reporting a crash caused by the result of `trace.getActiveSpan()` being truthy but not having a property `attributes`. it occurs when reading from the db in a custom express middleware. however, i'm not yet able to reproduce. → quick fix and follow-up

fix: add resilience to attributes handling

---

test/metrics.test.js
test/tracing-messaging.js
test/tracing.test.js

Refactoring to use `require('node:timers/promises').setTimeout` rather than `require('util').promisify(setTimeout)`.
No need to promisify a function as there's a native promise version of that: [Timers Promises API](https://nodejs.org/api/timers.html#timerspromisessettimeoutdelay-value-options)

refactor: Use node:timers/promises/setTimeout

---

lib/tracing/trace.js

Trace hana no params:
Trace hana with params:

add tracing with sql with out parameters for cap-js/hana

---

lib/tracing/trace.js

Putting a messaging service at a different name then messaging currently leads to:
TypeError: Cannot read properties of undefined (reading 'queued')
at trace (/Users/soeren.leibach/Projects/clouddatatransport/node_modules/@cap-js/telemetry/lib/tracing/trace.js:257:23)
at FileBasedMessaging.emit (/Users/soeren.leibach/Projects/clouddatatransport/node_modules/@cap-js/telemetry/lib/tracing/cds.js:39:14)
at module.exports (/Users/soeren.leibach/Projects/clouddatatransport/srv/code/transports-on-emitusage-logic.js:38:18)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async next (/Users/soeren.leibach/Projects/clouddatatransport/node_modules/@sap/cds/lib/srv/srv-dispatch.js:61:17)
at async TransportService.handle …

use correct service config in telemetry for messaging services

---

lib/exporter/ConsoleMetricExporter.js
lib/tracing/trace.js
test/metrics-outbox-disabled.test.js
test/metrics-outbox-multitenant.test.js
test/metrics-outbox.test.js

With unhandled unbound actions now throwing, tests without a dedicated handler for the `call` action of the `ExternalService`, used to simulate an external service to use in `.queued` / `.outboxed`, would throw and mess up the test expectations.

chore: adopt tests to unhandled action throws
